export enum DrivingCategory {
    MOFA = 'MOFA',
    A = 'A',
    AM = 'AM',
    A1 = 'A1',
    A2 = 'A2',
    B = 'B',
    B96 = 'B96',
    BE = 'BE',
    C1 = 'C1',
    C1E = 'C1E',
    C = 'C',
    CE = 'CE',
    D1 = 'D1',
    D1E = 'D1E',
    D = 'D',
    DE = 'DE',
    T = 'T',
    L = 'L'
}
